local T = dofile("tests/runner.lua")
dofile("tests/mock_platform.lua")
dofile("LOVE-WrapLua/OneLua/graphics.lua")

-- ── Color ────────────────────────────────────────────────────────
T.describe("love.graphics.setColor / getColor", function()
    T.it("stores 0-1 components and returns them", function()
        love.graphics.setColor(0.5, 0.25, 1.0, 0.8)
        local r, g, b, a = love.graphics.getColor()
        T.near(r, 0.5); T.near(g, 0.25); T.near(b, 1.0); T.near(a, 0.8)
    end)

    T.it("alpha defaults to 1 when omitted", function()
        love.graphics.setColor(1, 0, 0)
        local _, _, _, a = love.graphics.getColor()
        T.near(a, 1)
    end)

    T.it("accepts a table argument", function()
        love.graphics.setColor({0.1, 0.2, 0.3, 0.4})
        local r, g, b, a = love.graphics.getColor()
        T.near(r, 0.1); T.near(g, 0.2); T.near(b, 0.3); T.near(a, 0.4)
    end)

    T.it("maps to 0-255 platform color correctly (white stays white)", function()
        love.graphics.setColor(1, 1, 1, 1)
        local c = lv1lua.current.color
        T.eq(c.r, 255); T.eq(c.g, 255); T.eq(c.b, 255); T.eq(c.a, 255)
    end)

    T.it("maps 0.5 to 128", function()
        love.graphics.setColor(0.5, 0.5, 0.5, 1)
        T.eq(lv1lua.current.color.r, 128)
    end)
end)

T.describe("love.graphics.setBackgroundColor / getBackgroundColor", function()
    T.it("stores and returns background color", function()
        love.graphics.setBackgroundColor(0.1, 0.2, 0.3)
        local r, g, b = love.graphics.getBackgroundColor()
        T.near(r, 0.1); T.near(g, 0.2); T.near(b, 0.3)
    end)
end)

-- ── Transform stack ──────────────────────────────────────────────
T.describe("love.graphics transform stack", function()
    T.it("transformPoint with identity returns the same point", function()
        love.graphics.reset()
        local x, y = love.graphics.transformPoint(5, 10)
        T.near(x, 5); T.near(y, 10)
    end)

    T.it("translate shifts transformPoint result", function()
        love.graphics.reset()
        love.graphics.translate(100, 50)
        local x, y = love.graphics.transformPoint(0, 0)
        T.near(x, 100)
        T.near(y, 50)
    end)

    T.it("scale multiplies transformPoint", function()
        love.graphics.reset()
        love.graphics.scale(2, 3)
        local x, y = love.graphics.transformPoint(4, 5)
        T.near(x, 8)
        T.near(y, 15)
    end)

    T.it("origin() resets current transform level to identity", function()
        love.graphics.reset()
        love.graphics.translate(999, 999)
        love.graphics.origin()
        local x, y = love.graphics.transformPoint(0, 0)
        T.near(x, 0); T.near(y, 0)
    end)

    T.it("push/pop isolates transforms", function()
        love.graphics.reset()
        love.graphics.push()
        love.graphics.translate(200, 200)
        love.graphics.pop()
        local x, y = love.graphics.transformPoint(0, 0)
        T.near(x, 0); T.near(y, 0)
    end)

    T.it("inverseTransformPoint undoes transformPoint", function()
        love.graphics.reset()
        love.graphics.scale(2, 2)
        love.graphics.translate(10, 20)
        local tx, ty = love.graphics.transformPoint(5, 5)
        local ix, iy = love.graphics.inverseTransformPoint(tx, ty)
        T.near(ix, 5, 1e-4)
        T.near(iy, 5, 1e-4)
    end)
end)

-- ── Screen metrics ───────────────────────────────────────────────
T.describe("love.graphics screen info", function()
    T.it("getDimensions returns screenWidth x screenHeight", function()
        lv1lua.screenWidth = 960; lv1lua.screenHeight = 544
        local w, h = love.graphics.getDimensions()
        T.eq(w, 960); T.eq(h, 544)
    end)

    T.it("getWidth / getHeight match screenWidth / screenHeight", function()
        T.eq(love.graphics.getWidth(),  lv1lua.screenWidth)
        T.eq(love.graphics.getHeight(), lv1lua.screenHeight)
    end)

    T.it("isActive returns true", function()
        T.ok(love.graphics.isActive())
    end)

    T.it("isGammaCorrect returns false", function()
        T.nok(love.graphics.isGammaCorrect())
    end)
end)

-- ── Line width ───────────────────────────────────────────────────
T.describe("love.graphics setLineWidth / getLineWidth", function()
    T.it("setLineWidth stores the value", function()
        love.graphics.setLineWidth(3)
        T.eq(love.graphics.getLineWidth(), 3)
    end)

    T.it("setLineWidth nil resets to 1", function()
        love.graphics.setLineWidth(nil)
        T.eq(love.graphics.getLineWidth(), 1)
    end)
end)

-- ── Blend mode stub ──────────────────────────────────────────────
T.describe("love.graphics setBlendMode / getBlendMode", function()
    T.it("stores and returns the blend mode string", function()
        love.graphics.setBlendMode("add")
        local mode = love.graphics.getBlendMode()
        T.eq(mode, "add")
    end)
end)

-- ── Font ─────────────────────────────────────────────────────────
T.describe("love.graphics.newFont / setFont / getFont", function()
    T.it("newFont returns an object with getWidth/getHeight", function()
        local f = love.graphics.newFont(nil, 20)
        T.ok(f.getWidth,  "should have getWidth")
        T.ok(f.getHeight, "should have getHeight")
    end)

    T.it("getHeight returns the font size", function()
        local f = love.graphics.newFont(nil, 16)
        T.eq(f:getHeight(), 16)
    end)

    T.it("setFont / getFont roundtrip", function()
        local f = love.graphics.newFont(nil, 24)
        love.graphics.setFont(f)
        T.ok(love.graphics.getFont() == f)
    end)
end)

-- ── Quad ─────────────────────────────────────────────────────────
T.describe("love.graphics.newQuad", function()
    T.it("getViewport returns construction arguments", function()
        local q = love.graphics.newQuad(10, 20, 64, 32, 256, 128)
        local x, y, w, h = q:getViewport()
        T.eq(x, 10); T.eq(y, 20); T.eq(w, 64); T.eq(h, 32)
    end)

    T.it("getTextureDimensions returns sw/sh", function()
        local q = love.graphics.newQuad(0, 0, 32, 32, 512, 256)
        local sw, sh = q:getTextureDimensions()
        T.eq(sw, 512); T.eq(sh, 256)
    end)

    T.it("accepts an image object for dimensions", function()
        local img = love.graphics.newImage("dummy.png")
        local q   = love.graphics.newQuad(0, 0, 32, 32, img)
        local sw, sh = q:getTextureDimensions()
        T.eq(sw, img:getWidth())
        T.eq(sh, img:getHeight())
    end)
end)

-- ── newImage ─────────────────────────────────────────────────────
T.describe("love.graphics.newImage", function()
    T.it("returns object with getWidth/getHeight", function()
        local img = love.graphics.newImage("test.png")
        T.ok(img.getWidth,  "should have getWidth")
        T.ok(img.getHeight, "should have getHeight")
    end)

    T.it("getDimensions returns two numbers", function()
        local img = love.graphics.newImage("test.png")
        local w, h = img:getDimensions()
        T.istype(w, "number"); T.istype(h, "number")
    end)
end)

-- ── SpriteBatch ──────────────────────────────────────────────────
T.describe("love.graphics.newSpriteBatch", function()
    T.it("getCount starts at 0", function()
        local img = love.graphics.newImage("sprite.png")
        local sb  = love.graphics.newSpriteBatch(img, 100)
        T.eq(sb:getCount(), 0)
    end)

    T.it("add increments count", function()
        local img = love.graphics.newImage("sprite.png")
        local sb  = love.graphics.newSpriteBatch(img, 100)
        sb:add(0, 0)
        sb:add(10, 10)
        T.eq(sb:getCount(), 2)
    end)

    T.it("clear resets count to 0", function()
        local img = love.graphics.newImage("sprite.png")
        local sb  = love.graphics.newSpriteBatch(img, 100)
        sb:add(0, 0); sb:add(10, 10)
        sb:clear()
        T.eq(sb:getCount(), 0)
    end)

    T.it("getImage returns the source image", function()
        local img = love.graphics.newImage("sprite.png")
        local sb  = love.graphics.newSpriteBatch(img, 100)
        T.ok(sb:getImage() == img)
    end)
end)

-- ── Text / TextBatch ─────────────────────────────────────────────
T.describe("love.graphics.newText", function()
    T.it("constructor without text has 0 dimensions", function()
        local fnt = love.graphics.newFont(nil, 14)
        local txt = love.graphics.newText(fnt)
        T.eq(txt:getWidth(), 0); T.eq(txt:getHeight(), 0)
    end)

    T.it("set stores text and updates dimensions", function()
        local fnt = love.graphics.newFont(nil, 14)
        local txt = love.graphics.newText(fnt)
        txt:set("hello")
        T.ok(txt:getWidth() > 0, "width should be positive after set")
    end)

    T.it("getFont returns the font passed to constructor", function()
        local fnt = love.graphics.newFont(nil, 14)
        local txt = love.graphics.newText(fnt)
        T.ok(txt:getFont() == fnt)
    end)

    T.it("newTextBatch is an alias for newText", function()
        T.ok(love.graphics.newTextBatch == love.graphics.newText)
    end)
end)

-- ── Canvas stub ──────────────────────────────────────────────────
T.describe("love.graphics.newCanvas", function()
    T.it("returns object with getDimensions", function()
        local c = love.graphics.newCanvas(320, 240)
        local w, h = c:getDimensions()
        T.eq(w, 320); T.eq(h, 240)
    end)

    T.it("renderTo calls the callback", function()
        local c = love.graphics.newCanvas(64, 64)
        local called = false
        c:renderTo(function() called = true end)
        T.ok(called)
    end)
end)

-- ── Shader stub ──────────────────────────────────────────────────
T.describe("love.graphics.newShader", function()
    T.it("returns object without crashing", function()
        local s = love.graphics.newShader("void effect(){}")
        T.istype(s, "table")
    end)

    T.it("hasUniform always returns false", function()
        local s = love.graphics.newShader()
        T.nok(s:hasUniform("myUniform"))
    end)
end)

-- ── Mesh stub ────────────────────────────────────────────────────
T.describe("love.graphics.newMesh", function()
    T.it("getVertexCount matches argument for integer input", function()
        local m = love.graphics.newMesh(12, "fan")
        T.eq(m:getVertexCount(), 12)
    end)
end)

-- ── Stencil stub ─────────────────────────────────────────────────
T.describe("love.graphics stencil stubs", function()
    T.it("stencil calls the function argument", function()
        local called = false
        love.graphics.stencil(function() called = true end)
        T.ok(called)
    end)

    T.it("getStencilTest returns 'always', 0", function()
        local mode, val = love.graphics.getStencilTest()
        T.eq(mode, "always"); T.eq(val, 0)
    end)
end)

-- ── getStats / getRendererInfo ────────────────────────────────────
T.describe("love.graphics.getStats / getRendererInfo", function()
    T.it("getStats returns a table", function()
        T.istype(love.graphics.getStats(), "table")
    end)

    T.it("getRendererInfo returns four strings", function()
        local a, b, c, d = love.graphics.getRendererInfo()
        T.istype(a, "string"); T.istype(b, "string")
    end)
end)

-- ── Scissor ──────────────────────────────────────────────────────
T.describe("love.graphics.setScissor / getScissor", function()
    T.it("getScissor returns nil when no scissor is set", function()
        love.graphics.reset()
        T.ok(love.graphics.getScissor() == nil)
    end)

    T.it("setScissor stores and getScissor retrieves it", function()
        love.graphics.reset()
        love.graphics.setScissor(10, 20, 100, 50)
        local x, y, w, h = love.graphics.getScissor()
        T.eq(x, 10); T.eq(y, 20); T.eq(w, 100); T.eq(h, 50)
    end)

    T.it("setScissor with no args clears scissor", function()
        love.graphics.reset()
        love.graphics.setScissor(0, 0, 50, 50)
        love.graphics.setScissor()
        T.ok(love.graphics.getScissor() == nil)
    end)
end)

-- ── Primitive smoke tests (no crash) ─────────────────────────────
T.describe("love.graphics primitives (no-crash smoke)", function()
    love.graphics.setColor(1, 0, 0)

    T.it("rectangle fill does not crash", function()
        love.graphics.rectangle("fill", 10, 10, 50, 30)
    end)
    T.it("rectangle line does not crash", function()
        love.graphics.rectangle("line", 10, 10, 50, 30)
    end)
    T.it("circle fill does not crash", function()
        love.graphics.circle("fill", 50, 50, 20)
    end)
    T.it("circle line does not crash", function()
        love.graphics.circle("line", 50, 50, 20)
    end)
    T.it("ellipse does not crash", function()
        love.graphics.ellipse("fill", 50, 50, 30, 20)
    end)
    T.it("polygon fill does not crash", function()
        love.graphics.polygon("fill", {0,0, 50,0, 50,50, 0,50})
    end)
    T.it("polygon line does not crash", function()
        love.graphics.polygon("line", {0,0, 50,0, 50,50, 0,50})
    end)
    T.it("arc does not crash", function()
        love.graphics.arc("fill", "pie", 50, 50, 30, 0, math.pi)
    end)
    T.it("line does not crash", function()
        love.graphics.line(0,0, 10,10, 20,0)
    end)
    T.it("points does not crash", function()
        love.graphics.points(1,1, 2,2, 3,3)
    end)
end)

io.write("\n=== love.graphics (OneLua) ===\n")
return T.summary()
