name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lua: ["5.1", "5.3", "5.4", "luajit-2.1.0-beta3"]
    name: lua ${{ matrix.lua }}
    steps:
      - uses: actions/checkout@v4

      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.lua }}

      - name: Run test suite
        run: lua tests/run_all.lua
